export const BOOKS_FETCH_SUCCESS = "BOOKS_FETCH_SUCCESS";
export const BOOK_FETCH_SUCCESS = "BOOK_FETCH_SUCCESS";
export const AUTHOR_BOOKS_FETCH_SUCCESS = "AUTHOR_BOOKS_FETCH_SUCCESS";
export const AUTHORS_FETCH_SUCCESS = "AUTHORS_FETCH_SUCCESS";
export const AUTHOR_FETCH_SUCCESS = "AUTHOR_FETCH_SUCCESS";
